app:
    resource: '@AppBundle/Controller/'
    type: annotation

student_chart:
   path: '/studentChartAction'
   defaults: { _controller: AppBundle:Default:studentChart}

mark_chart:
   path: '/markChartAction'
   defaults: { _controller: AppBundle:Default:markChart}